
USE Yelp_Business_Analytics;

--1 Which cities have the highest number of businesses?

SELECT TOP 10 city, state, COUNT(*) AS business_count
FROM business 
GROUP BY city, state
ORDER BY business_count DESC

--2  Which cities have the highest average business rating?

SELECT TOP 10  city, state, COUNT(*) AS business_count,
ROUND(AVG(stars), 2) AS average_rating
FROM business
GROUP BY city, state
HAVING COUNT(*) >= 100
ORDER BY average_rating DESC;

-- Q3. Which cities have the highest customer engagement?
-- Business logic:
-- Measures total review volume generated by businesses in each city.

SELECT TOP 10 city, state,
    COUNT(*) AS business_count,
    SUM(review_count) AS total_reviews,
    ROUND(AVG(review_count), 2) AS avg_reviews_per_business
FROM business
GROUP BY
    city,
    state
HAVING COUNT(*) >= 100
ORDER BY
    total_reviews DESC;

---4  Which cities have high business concentration but relatively low customer engagement?

SELECT
    city,
    state,
    COUNT(*) AS business_count,
    SUM(review_count) AS total_reviews,
    ROUND(AVG(review_count), 2) AS avg_reviews_per_business
FROM business
GROUP BY
    city,
    state
HAVING
    COUNT(*) >= 5000
    AND AVG(review_count) < 50
ORDER BY
    business_count DESC;


--5  Which business categories have the largest business presence?

SELECT TOP 15
    c.category,
    COUNT(DISTINCT bc.business_id) AS business_count
FROM business_category bc
JOIN category c
    ON bc.category_id = c.category_id
GROUP BY
    c.category
ORDER BY
    business_count DESC;


----6 Which business categories have the highest average rating?

SELECT TOP 15
    c.category,
    COUNT(DISTINCT b.business_id) AS business_count,
    ROUND(AVG(b.stars), 2) AS average_rating
FROM business b
JOIN business_category bc
    ON b.business_id = bc.business_id
JOIN category c
    ON bc.category_id = c.category_id
GROUP BY
    c.category
HAVING COUNT(DISTINCT b.business_id) >= 100
ORDER BY
    average_rating DESC;

----7 Which business categories generate the highest review volume?


SELECT TOP 15
    c.category,
    COUNT(DISTINCT b.business_id) AS business_count,
    SUM(b.review_count) AS total_reviews,
    ROUND(AVG(b.review_count), 2) AS avg_reviews_per_business
FROM business b
JOIN business_category bc
    ON b.business_id = bc.business_id
JOIN category c
    ON bc.category_id = c.category_id
GROUP BY
    c.category
HAVING COUNT(DISTINCT b.business_id) >= 100
ORDER BY
    total_reviews DESC;


--8 Which categories combine strong ratings with strong customer engagement?

USE Yelp_Business_Analytics;
GO

WITH CategoryMetrics AS
(
    SELECT
        c.category,
        COUNT(DISTINCT b.business_id) AS business_count,
        AVG(b.stars) AS average_rating,
        AVG(b.review_count) AS avg_reviews_per_business
    FROM business b
    JOIN business_category bc
        ON b.business_id = bc.business_id
    JOIN category c
        ON bc.category_id = c.category_id
    GROUP BY
        c.category
    HAVING COUNT(DISTINCT b.business_id) >= 100
)
SELECT
    category,
    business_count,
    ROUND(average_rating, 2) AS average_rating,
    ROUND(avg_reviews_per_business, 2) AS avg_reviews_per_business
FROM CategoryMetrics
WHERE average_rating >= 4.00
  AND avg_reviews_per_business >= 50
ORDER BY
    average_rating DESC,
    avg_reviews_per_business DESC;

---9 Which businesses are the top performers?
USE Yelp_Business_Analytics;
GO

WITH BusinessMetrics AS
(
    SELECT
        business_id,
        name,
        city,
        state,
        stars AS rating,
        review_count,
        (stars * LOG10(review_count + 1)) AS performance_score
    FROM business
    WHERE review_count >= 100
)
SELECT TOP 20
    business_id,
    name,
    city,
    state,
    rating,
    review_count,
    ROUND(performance_score, 2) AS performance_score
FROM BusinessMetrics
ORDER BY
    performance_score DESC;


---- Popular but Weak Businesses
SELECT TOP 20
    business_id,
    name,
    city,
    state,
    stars AS rating,
    review_count
FROM business
WHERE review_count >= 1000
  AND stars < 3.6
ORDER BY
    review_count DESC;

--- 11 Which businesses have high ratings but relatively low review volume?
USE Yelp_Business_Analytics;
GO

SELECT TOP 20
    business_id,
    name,
    city,
    state,
    stars AS rating,
    review_count
FROM business
WHERE stars >= 4.5
  AND review_count BETWEEN 50 AND 200
ORDER BY
    stars DESC,
    review_count ASC;


-- 12 Which city × category combinations show the strongest business opportunity?


SELECT TOP 30
    b.city,
    b.state,
    c.category,
    COUNT(DISTINCT b.business_id) AS business_count,
    ROUND(AVG(b.stars), 2) AS average_rating,
    ROUND(AVG(b.review_count), 2) AS avg_reviews_per_business,
    SUM(b.review_count) AS total_reviews
FROM business b
JOIN business_category bc
    ON b.business_id = bc.business_id
JOIN category c
    ON bc.category_id = c.category_id
GROUP BY
    b.city,
    b.state,
    c.category
HAVING
    COUNT(DISTINCT b.business_id) >= 10
    AND AVG(b.stars) >= 4.0
    AND AVG(b.review_count) >= 50
ORDER BY
    average_rating DESC,
    avg_reviews_per_business DESC;


--- Creating Views for bi
--1 VIEW
USE Yelp_Business_Analytics;
GO

CREATE OR ALTER VIEW vw_Business_Analysis AS
SELECT
    business_id,
    name,
    city,
    state,
    stars AS rating,
    review_count,
    is_open,
    business_status
FROM business;
GO

--- 2 VIEW
USE Yelp_Business_Analytics;
GO

CREATE OR ALTER VIEW vw_Category_Analysis AS
SELECT
    c.category,
    COUNT(DISTINCT b.business_id) AS business_count,
    ROUND(AVG(b.stars), 2) AS average_rating,
    ROUND(AVG(b.review_count), 2) AS avg_reviews_per_business,
    SUM(b.review_count) AS total_reviews
FROM business b
JOIN business_category bc

--- VIEW 3
USE Yelp_Business_Analytics;
GO

CREATE OR ALTER VIEW vw_Market_Opportunity AS
SELECT
    b.city,
    b.state,
    c.category,
    COUNT(DISTINCT b.business_id) AS business_count,
    ROUND(AVG(b.stars), 2) AS average_rating,
    ROUND(AVG(b.review_count), 2) AS avg_reviews_per_business,
    SUM(b.review_count) AS total_reviews
FROM business b
JOIN business_category bc
    ON b.business_id = bc.business_id
JOIN category c
    ON bc.category_id = c.category_id
GROUP BY
    b.city,
    b.state,
    c.category
HAVING
    COUNT(DISTINCT b.business_id) >= 10
    AND AVG(b.stars) >= 4.0
    AND AVG(b.review_count) >= 50;
GO
    ON b.business_id = bc.business_id
JOIN category c
    ON bc.category_id = c.category_id
GROUP BY
    c.category;
GO


--- FOR VERIFY

USE Yelp_Business_Analytics;
GO

SELECT
    'Business Analysis' AS view_name,
    COUNT(*) AS row_count
FROM vw_Business_Analysis

UNION ALL

SELECT
    'Category Analysis',
    COUNT(*)
FROM vw_Category_Analysis

UNION ALL

SELECT
    'Market Opportunity',
    COUNT(*)
FROM vw_Market_Opportunity;